#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, displays occurrence numbers, and sorts the data.

# Use awk to extract IP address (field 1) and HTTP status code (field 9)
# Count occurrences and store in an associative array
awk '{arr[$1 " " $9]++} END {for (i in arr) {split(i, a, " "); print arr[i], a[1], a[2]}}' apache-access.log | sort -nr
