#!/usr/bin/env bash
# Header for the process list
printf "%-10s %-10s\n" "USER" "START"
# List all processes and format the output
ps axo user,start --no-headers | \
awk '{ printf "%-10s %-10s\n", $1, $2 }'
